"""change nik from integer to decimal

Revision ID: 44314aaf8ade
Revises: d1f660dbe03c
Create Date: 2018-11-07 13:31:23.001950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44314aaf8ade'
down_revision = 'd1f660dbe03c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
