"""chane table dataCatin to DataCatin

Revision ID: 477eb05c3dd9
Revises: f889c272e3ae
Create Date: 2018-11-07 04:09:06.541881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '477eb05c3dd9'
down_revision = 'f889c272e3ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
