"""tambahkan kolom tanggal_daftar;


Revision ID: 82097126f02a
Revises: e070c91ed2d8
Create Date: 2018-11-08 13:49:22.559946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82097126f02a'
down_revision = 'e070c91ed2d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_catin', sa.Column('tanggal_daftar', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_catin', 'tanggal_daftar')
    # ### end Alembic commands ###
