"""add colom is_public2

Revision ID: 83f5b0df3839
Revises: 
Create Date: 2018-11-08 02:19:26.420619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83f5b0df3839'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_catin', sa.Column('is_public', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_catin', 'is_public')
    # ### end Alembic commands ###
