""".

Revision ID: a197687400d8
Revises: 5fe72b1a073b
Create Date: 2018-11-08 02:29:42.030965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a197687400d8'
down_revision = '5fe72b1a073b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_catin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('NIK_catin_laki_laki', sa.DECIMAL(), nullable=True),
    sa.Column('nama_catin_laki_laki', sa.String(length=100), nullable=True),
    sa.Column('NIK_catin_perempuan', sa.DECIMAL(), nullable=True),
    sa.Column('nama_catin_perempuan', sa.String(length=100), nullable=True),
    sa.Column('jadwal_nikah', sa.Date(), nullable=True),
    sa.Column('jam', sa.Time(), nullable=True),
    sa.Column('tempat_pelaksaan_nikah', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('NIK_catin_laki_laki'),
    sa.UniqueConstraint('NIK_catin_perempuan')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_catin')
    # ### end Alembic commands ###
