"""change kolom taggal_daftar datatype from date to datetime1

Revision ID: a6bb87c48d04
Revises: e5804575fcc3
Create Date: 2018-11-08 14:23:50.596147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6bb87c48d04'
down_revision = 'e5804575fcc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
