"""tambah kolom status pendaftaran

Revision ID: ae2ab6262ea2
Revises: 
Create Date: 2018-11-07 06:03:19.364921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae2ab6262ea2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('post', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('status_pendaftaran', sa.Enum('Sedang di proses', 'Diterima', name='status_pendaftaran'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('data_catin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('NIK_catin_laki_laki', sa.Integer(), nullable=True),
    sa.Column('nama_catin_laki_laki', sa.String(length=100), nullable=True),
    sa.Column('NIK_catin_perempuan', sa.Integer(), nullable=True),
    sa.Column('nama_catin_perempuan', sa.String(length=100), nullable=True),
    sa.Column('jadwal_nikah', sa.DateTime(), nullable=True),
    sa.Column('tempat_pelaksaan_nikah', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles_users')
    op.drop_table('data_catin')
    op.drop_table('user')
    op.drop_table('role')
    op.drop_table('content')
    # ### end Alembic commands ###
