"""change data type jadwal_bikag from datetiem to date

Revision ID: dcd6ba241701
Revises: ae2ab6262ea2
Create Date: 2018-11-07 10:02:32.784399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcd6ba241701'
down_revision = 'ae2ab6262ea2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
