"""change kolom taggal_daftar datatype from date to datetime

Revision ID: e5804575fcc3
Revises: 82097126f02a
Create Date: 2018-11-08 14:16:51.976966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5804575fcc3'
down_revision = '82097126f02a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
