"""change kolom taggal_daftar datatype from date to datetime2

Revision ID: eaa11335f860
Revises: a6bb87c48d04
Create Date: 2018-11-08 14:23:56.776915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaa11335f860'
down_revision = 'a6bb87c48d04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
