"""change kolom name on dataCatin table

Revision ID: f889c272e3ae
Revises: 4c88e32c2639
Create Date: 2018-11-07 04:07:12.356248

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f889c272e3ae'
down_revision = '4c88e32c2639'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_catin', sa.Column('NIK_catin_laki_laki', sa.Integer(), nullable=True))
    op.add_column('data_catin', sa.Column('NIK_catin_perempuan', sa.Integer(), nullable=True))
    op.add_column('data_catin', sa.Column('jadwal_nikah', sa.DateTime(), nullable=True))
    op.add_column('data_catin', sa.Column('nama_catin_laki_laki', sa.String(length=100), nullable=True))
    op.add_column('data_catin', sa.Column('nama_catin_perempuan', sa.String(length=100), nullable=True))
    op.add_column('data_catin', sa.Column('tempat_pelaksaan_nikah', sa.String(), nullable=True))
    op.drop_column('data_catin', 'catinLakiLakiName')
    op.drop_column('data_catin', 'nikCatinLakiLaki')
    op.drop_column('data_catin', 'tempatPelaksanaanNikah')
    op.drop_column('data_catin', 'catinPerempuanName')
    op.drop_column('data_catin', 'jadwalNikah')
    op.drop_column('data_catin', 'nikCatinPerempuan')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_catin', sa.Column('nikCatinPerempuan', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('data_catin', sa.Column('jadwalNikah', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('data_catin', sa.Column('catinPerempuanName', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('data_catin', sa.Column('tempatPelaksanaanNikah', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('data_catin', sa.Column('nikCatinLakiLaki', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('data_catin', sa.Column('catinLakiLakiName', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('data_catin', 'tempat_pelaksaan_nikah')
    op.drop_column('data_catin', 'nama_catin_perempuan')
    op.drop_column('data_catin', 'nama_catin_laki_laki')
    op.drop_column('data_catin', 'jadwal_nikah')
    op.drop_column('data_catin', 'NIK_catin_perempuan')
    op.drop_column('data_catin', 'NIK_catin_laki_laki')
    # ### end Alembic commands ###
