"""add kolom jam

Revision ID: fb3ac8543383
Revises: dcd6ba241701
Create Date: 2018-11-07 10:04:44.233649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb3ac8543383'
down_revision = 'dcd6ba241701'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_catin', sa.Column('jam', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_catin', 'jam')
    # ### end Alembic commands ###
